DROP TABLE VETERINARNI_ZAZNAM CASCADE CONSTRAINTS;
DROP TABLE ADOPCE            CASCADE CONSTRAINTS;
DROP TABLE ZVIRE             CASCADE CONSTRAINTS;
DROP TABLE VETERINAR         CASCADE CONSTRAINTS;
DROP TABLE PECOVATEL         CASCADE CONSTRAINTS;
 
 
CREATE TABLE ADOPCE 
    ( 
     CISLO_ADOPCE           NUMBER  NOT NULL , 
     POPLATEK               NUMBER  NOT NULL , 
     DATUM_ADOPCE           DATE  NOT NULL , 
     POTREBA_NAVSTEVY       VARCHAR2 (3 CHAR)  NOT NULL , 
     PECOVATEL_ID_PECOVATEL NUMBER  NOT NULL , 
     ZVIRE_ID_ZVIRE         NUMBER  NOT NULL 
    ) 
;
 
ALTER TABLE ADOPCE 
    ADD 
    CHECK (POTREBA_NAVSTEVY IN ('ano', 'ne')) 
;
CREATE UNIQUE INDEX ADOPCE__IDX ON ADOPCE 
    ( 
     ZVIRE_ID_ZVIRE ASC 
    ) 
;
 
ALTER TABLE ADOPCE 
    ADD CONSTRAINT ADOPCE_PK PRIMARY KEY ( CISLO_ADOPCE ) ;
 
ALTER TABLE ADOPCE 
    ADD CONSTRAINT ADOPCE__UN UNIQUE ( ZVIRE_ID_ZVIRE ) ;
 
CREATE TABLE PECOVATEL 
    ( 
     ID_PECOVATEL NUMBER  NOT NULL , 
     JMENO        VARCHAR2 (50 CHAR)  NOT NULL , 
     TELEFON      NUMBER  NOT NULL , 
     ADRESA       VARCHAR2 (255 CHAR)  NOT NULL 
    ) 
;
 
ALTER TABLE PECOVATEL 
    ADD CONSTRAINT PECOVATEL_PK PRIMARY KEY ( ID_PECOVATEL ) ;
 
CREATE TABLE VETERINAR 
    ( 
     ID_VETERINAR  NUMBER  NOT NULL , 
     JMENO         VARCHAR2 (50 CHAR)  NOT NULL , 
     TELEFON       NUMBER  NOT NULL , 
     JMENO_KLINIKY VARCHAR2 (50)  NOT NULL , 
     SPECIALIZACE  VARCHAR2 (30 CHAR)  NOT NULL 
    ) 
;
 
ALTER TABLE VETERINAR 
    ADD CONSTRAINT VETERINAR_PK PRIMARY KEY ( ID_VETERINAR ) ;
 
CREATE TABLE VETERINARNI_ZAZNAM 
    ( 
     CISLO_ZAZNAMU          NUMBER  NOT NULL , 
     DATUM_VYSETRENI        DATE  NOT NULL , 
     DIAGNOZA               VARCHAR2 (400 CHAR)  NOT NULL , 
     LECBA                  VARCHAR2 (400 CHAR)  NOT NULL , 
     ZVIRE_ID_ZVIRE         NUMBER  NOT NULL , 
     VETERINAR_ID_VETERINAR NUMBER  NOT NULL 
    ) 
;
 
ALTER TABLE VETERINARNI_ZAZNAM 
    ADD CONSTRAINT VETERINARNI_ZAZNAM_PK PRIMARY KEY ( CISLO_ZAZNAMU, ZVIRE_ID_ZVIRE, VETERINAR_ID_VETERINAR ) ;
 
CREATE TABLE ZVIRE 
    ( 
     ID_ZVIRE               NUMBER  NOT NULL , 
     DRUH                   VARCHAR2 (30 CHAR)  NOT NULL , 
     DATUM_PRIJMU           DATE  NOT NULL , 
     POHLAVI                VARCHAR2 (1 CHAR)  NOT NULL , 
     JMENO                  VARCHAR2 (30 CHAR) , 
     PECOVATEL_ID_PECOVATEL NUMBER 
    ) 
;
 
ALTER TABLE ZVIRE 
    ADD 
    CHECK (POHLAVI IN ('f', 'm')) 
;
 
ALTER TABLE ZVIRE 
    ADD CONSTRAINT ZVIRE_PK PRIMARY KEY ( ID_ZVIRE ) ;
 
ALTER TABLE ADOPCE 
    ADD CONSTRAINT ADOPCE_PECOVATEL_FK FOREIGN KEY 
    ( 
     PECOVATEL_ID_PECOVATEL
    ) 
    REFERENCES PECOVATEL 
    ( 
     ID_PECOVATEL
    ) 
;
 
ALTER TABLE ADOPCE 
    ADD CONSTRAINT ADOPCE_ZVIRE_FK FOREIGN KEY 
    ( 
     ZVIRE_ID_ZVIRE
    ) 
    REFERENCES ZVIRE 
    ( 
     ID_ZVIRE
    ) 
;
 
ALTER TABLE VETERINARNI_ZAZNAM 
    ADD CONSTRAINT VET_ZAZNAM_VETERINAR_FK FOREIGN KEY 
    ( 
     VETERINAR_ID_VETERINAR
    ) 
    REFERENCES VETERINAR 
    ( 
     ID_VETERINAR
    ) 
;
 
ALTER TABLE VETERINARNI_ZAZNAM 
    ADD CONSTRAINT VET_ZAZNAM_ZVIRE_FK FOREIGN KEY 
    ( 
     ZVIRE_ID_ZVIRE
    ) 
    REFERENCES ZVIRE 
    ( 
     ID_ZVIRE
    ) 
;
 
ALTER TABLE ZVIRE 
    ADD CONSTRAINT ZVIRE_PECOVATEL_FK FOREIGN KEY 
    ( 
     PECOVATEL_ID_PECOVATEL
    ) 
    REFERENCES PECOVATEL 
    ( 
     ID_PECOVATEL
    ) 
;
